-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.registration_tokens
(
    id serial NOT NULL,
    token character varying(64) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    used boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT registration_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT registration_tokens_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.token
(
    id serial NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    datetime timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remarks character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'unused'::character varying,
    CONSTRAINT token_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);
END;